#+TITLE: Zellij config

** Deploy

#+begin_src elisp :output none
  ;; local variables
  (setq-local dst-dir (expand-file-name "~/.config/zellij"))
  (setq-local tmp-dir "zellij")
  (setq-local backup-prefix (format-time-string "%Y-%m-%d_%H%M%S_"))
  ;; Make directories
  (make-directory tmp-dir t)
  (make-directory dst-dir t)
  ;; Generate files under tmp dir (./zellij)
  (org-babel-tangle-file "zellij.org")
  ;; Save new file
  (dolist (i (list "config.kdl"))
    (let ((src-file-path (file-name-concat tmp-dir i))
          (dst-file-path (file-name-concat dst-dir i))
          (bak-file-path (file-name-concat tmp-dir (concat backup-prefix i))))
      ;; Take backup
      (if (file-exists-p dst-file-path)
          (copy-file dst-file-path bak-file-path t)
        nil)
      ;; deploy
      (copy-file src-file-path dst-file-path t)))
#+end_src

#+RESULTS:

** Configuration

Header

#+begin_src conf :tangle zellij/config.kdl
// Zellij config.kdl file generated by zellij.org file
#+end_src

*** Keybindings
**** Start
#+begin_src conf :tangle zellij/config.kdl
  // Keybindings
  keybinds {
#+end_src

**** Lock, Unlock

- Use "Ctrl z" instead of "Ctrl g"
- normal mode <--[Ctrl z]--> lock mode

#+begin_src conf :tangle zellij/config.kdl
  unbind "Ctrl g"
  locked {
    bind "Ctrl z" { SwitchToMode "normal"; }
  }
  shared_except "locked" {
    bind "Ctrl z" { SwitchToMode "locked"; }
  }
#+end_src

**** Pane split

Bind "-" and "|" keys to splitting a pane.

#+begin_src conf :tangle zellij/config.kdl
  pane {
    bind "-" { NewPane "down"; }
    bind "|" { NewPane "right"; }
  }
  tmux {
    bind "-" { NewPane "down"; SwitchToMode "locked"; }
    bind "|" { NewPane "right"; SwitchToMode "locked"; }
  }
#+end_src

**** Toggle focus full screen

Change to Locked mode after switching to/from full screen.

#+begin_src conf :tangle zellij/config.kdl
  pane {
    bind "f" { ToggleFocusFullscreen; SwitchToMode "locked"; }
  }
#+end_src

**** Scroll

Use "locked" mode after switching to the scroll editor

#+begin_src conf :tangle zellij/config.kdl
    scroll {
        bind "e" { EditScrollback; SwitchToMode "locked"; }
    }
#+end_src

**** Close
#+begin_src conf :tangle zellij/config.kdl
  }
#+end_src

*** Plugins

Use default plugins.

*** Rest of the config

*Changes*

For more pace:
- "compact" layout (~default_layout~)
- "locked" mode (~default_mode~)
- No pane frame (~pane_frames~)

Use Emacs for scrollback editor:
~scrollback_editor~
Create a scroll back editor specific init file ~scroll-editor-init.el~

#+begin_src conf :tangle zellij/config.kdl
  default_layout "compact"
  default_mode "locked"
  pane_frames false
#+end_src

**** Copy to clipboard

***** Linux

#+begin_src conf :tangle (if (eq system-type 'gnu/linux) "zellij/config.kdl" "")
  copy_command "xclip -selection clipboard"
#+end_src

***** Mac

#+begin_src conf :tangle (if (eq system-type 'darwin) "zellij/config.kdl" "")
  copy_command "pbcopy"
#+end_src

**** Scrollback Editor

#+begin_src conf :tangle zellij/config.kdl
  scrollback_editor "scroll-editor.sh"
#+end_src

** Emacs as a Scroll Editor

Zellij utilize external text editor as a scroll editor, that is different from Tmux's approach.
When opening the scroll buffer, the editor point the first line of the scroll buffer, that I don't expected.
Personally, I want to see the LAST line of the scroll buffer, since it is shown on the screen in most cases.

Here is my current solution for opening a bottom of the scroll buffer.

Note:

Zellij configuration ~scrollback_editor~ cannot understand environment varialbe.
So, the executable must be written FULL path or specify the file name under the PATH.
Current approach is creating the ~scroll-editor.sh~ file under the ~$HOME/.local/bin~ directory assuming the directory is included in the PATH.

*** Emacs launch file - ~scroll-editor.sh~

#+begin_src bash :tangle ~/.local/bin/scroll-editor.sh :shebang "#!/usr/bin/env bash" :mkdirp yes
  # Launch Emacs for Zellij Scroll Editor

  # Find emacs path
  EMACS_PATHS=(
    "/usr/bin/emacs"
    "/Applications/Emacs.app/Contents/MacOS/Emacs"
  )
  # Find and run emacs
  for EMACS in ${EMACS_PATHS[@]}; do
    if [ -f "$EMACS" ]; then
      "$EMACS" -nw -Q -l "$HOME/.local/bin/scroll-editor-init.el" $@
    fi
  done
#+end_src

*** Emacs init file for scroll editor - ~scroll-editor-init.el~

#+begin_src conf :tangle ~/.local/bin/scroll-editor-init.el :mkdirp yes
  ;; Emacs init file for Zellij scroll editor
  ;; no menu
  (menu-bar-mode -1)
  ;; scroll down to the end of the buffer
  (add-hook 'find-file-hook 'end-of-buffer)
#+end_src
